### PR TITLE
Simplify process and instructions

### PR DESCRIPTION
**Pull request by s2t2**
Handle a single more flexible scenario for issue parsing - if we already have the user's handle from the event data, we can just use that. This will help simplify the instructions as well - we can just tell someone to say "RaiseHigh", so there is no confusion about using their specific handle.

### CODE REVIEW

**Comment by labarba** [comment]
hey @gwutrexl 👋 
@s2t2 is the new OSPO dev, and he offered some ideas for improvement here... have a look! 👁️

**Comment by gwutrexl** [comment]
Thanks ! @s2t2 
I'll review this with the team during our weekly Friday meeting. 
I don't imagine there will be any objection.

**Comment by gwutrexl** [comment]
and I have to apologize, 
I must've missed the initial pull request email. I certainly did not mean for this to sit this long.

**Comment by gwutrexl** [comment]
@s2t2 @labarba We've reviewed this morning and don't see a reason why we can't make this change. 
We appreciate the suggestion !

**Comment by ghfields** [comment]
@s2t2 Appreciate your efforts!

**Pull request merged**
